doctrine:
    dbal:
        default_connection: central
        connections:
            central:
                url: '%env(resolve:DATABASE_CENTRAL_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
            world:
                url: '%env(resolve:DATABASE_GAME_SERVER)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

    orm:
        default_entity_manager: central

        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
#        report_fields_where_declared: true
#        validate_xml_mapping: true



        entity_managers:

            central:
                connection: central
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Central:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Central'
                        prefix: App\Entity\Central
                    Common: &common
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Common'
                        prefix: App\Entity\Common
                identity_generation_preferences:
                    Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
            world:
                connection: world
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Common: *common
                    World:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/World'
                        prefix: App\Entity\World
                    Construction:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Modules/Construction/Entity'
                        prefix: App\Modules\Construction\Entity

                    Planet:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Modules/Planet/Model'
                        prefix: App\Modules\Planet\Model

                    Shared:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Modules/Shared/Model'
                        prefix: App\Modules\Shared\Model
                identity_generation_preferences:
                    Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity




when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
