liip_imagine:
    filter_sets:
      cache: ~
      building_thumb:
        quality: 75
        filters:
          thumbnail: { size: [128, 128], mode: outbound}
      building_header:
        quality: 100
        filters:
          thumbnail: { size: [256, 256], mode: outbound}