security:
  role_hierarchy:
    ROLE_DEITY: [ ALL_ROLES ]

    ROLE_RESOURCES_ADMIN:
      - ROLE_CAN_MAXIMIZE_STORAGE

    ROLE_CONSTRUCTIONS_ADMIN:
      - ROLE_CAN_TERMINATE_CONSTRUCTIONS

    ALL_ROLES:
      - ROLE_USER
      - ROLE_CONSTRUCTIONS_ADMIN
      - ROLE_RESOURCES_ADMIN
