twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        # Namespace & directory for components
        App\Twig\Components\: 'components/'
        App\Planet\Twig\:
            template_directory: '@Planet/components/'
            name_prefix: 'Planet'